import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Rebase Labs
        </h1>
        <div className={styles.grid}>
          <a href="https://github.com/Rebase-Labs" className={styles.card}>
            <h2>Github</h2>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
